# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7fafd2bea6a3d901a7335c62211c956c4b7adbf3e3ceb2d3ac3355ad2e0e0fcb180797b9341d4f34d3a89178d662927c857fb068c2414c745da05e7428bb168

test:
  secret_key_base: 1274086b454a52c7236c6bb7ba5b70a4effc57e372b8c62be792922c1836f39ee4d524951a2da6a332304959a76672be797eb959186902ccc506c551fdae24fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
